sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t hrektts/nginx-proxy .

script:
  - docker run -it -v /var/run/docker.sock:/tmp/docker.sock:ro hrektts/nginx-proxy echo "Hello World"
